
package dictionary;


import java.util.LinkedList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;


public class JFrame extends javax.swing.JFrame {

    /**
     * Creates new form JFrame
     */
    public JFrame() {
        setTitle("Dictionary");
        setLocationRelativeTo(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt = new javax.swing.JTextField();
        jSearch = new javax.swing.JButton();
        jAdd = new javax.swing.JButton();
        jDelete = new javax.swing.JButton();
        jReplace = new javax.swing.JButton();
        jSave = new javax.swing.JButton();
        sp = new javax.swing.JScrollPane();
        list = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResult = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtActionPerformed(evt);
            }
        });
        txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtKeyTyped(evt);
            }
        });
        getContentPane().add(txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 127, 26));

        jSearch.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tu Nguyen\\Documents\\NetBeansProjects\\Dictionary\\icon\\search.png")); // NOI18N
        jSearch.setText("Search");
        jSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchActionPerformed(evt);
            }
        });
        getContentPane().add(jSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 42, -1, -1));

        jAdd.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tu Nguyen\\Documents\\NetBeansProjects\\Dictionary\\icon\\add.png")); // NOI18N
        jAdd.setText("Add");
        jAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddActionPerformed(evt);
            }
        });
        getContentPane().add(jAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 0, -1, -1));

        jDelete.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tu Nguyen\\Documents\\NetBeansProjects\\Dictionary\\icon\\delete.png")); // NOI18N
        jDelete.setText("Delete");
        jDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(jDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 0, -1, -1));

        jReplace.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tu Nguyen\\Documents\\NetBeansProjects\\Dictionary\\icon\\icons8-edit-file-50.png")); // NOI18N
        jReplace.setText("Replace");
        jReplace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jReplaceActionPerformed(evt);
            }
        });
        getContentPane().add(jReplace, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 3, -1, 28));

        jSave.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tu Nguyen\\Documents\\NetBeansProjects\\Dictionary\\icon\\icons8-save-50.png")); // NOI18N
        jSave.setText("Save");
        jSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveActionPerformed(evt);
            }
        });
        getContentPane().add(jSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 0, -1, 30));

        list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                listMouseEntered(evt);
            }
        });
        list.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listValueChanged(evt);
            }
        });
        sp.setViewportView(list);

        getContentPane().add(sp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 161, 254));

        txtResult.setContentType("text/html"); // NOI18N
        txtResult.setFocusable(false);
        jScrollPane1.setViewportView(txtResult);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 273, 254));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tu Nguyen\\Documents\\NetBeansProjects\\Dictionary\\icon\\background (1).jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 350));

        pack();
    }// </editor-fold>                        
    
    private void jAddActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        DM.save();
        JFrameAdd jfa;
        jfa =new JFrameAdd();
        DM.save();
    }                                    

    private void jDeleteActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        DM.save();
        JFrameDelete jfd;
        jfd=new JFrameDelete();
        DM.save();
    }                                       

    private void jReplaceActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        DM.save();
        JFrameReplace jfr;
        jfr=new JFrameReplace();
        DM.save();
        
    }                                        
    DictionaryManagement DM=new DictionaryManagement();
    private void jSaveActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
        DM.save();
        JOptionPane.showMessageDialog(rootPane, "Lưu thành công!");
    }                                     

    private void jSearchActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        if(txt.getText().trim().equals("")==true){
            JOptionPane.showMessageDialog(rootPane, "Hãy nhập từ cần tra");
        }
        else {
            if(DM.dictionaryLookup(txt.getText().trim())==true){
                String a=DM.JMean1(txt.getText().trim());
                txtResult.setText(a);
            }
            else {
                JOptionPane.showMessageDialog(rootPane, "Từ không có trong từ điển!");
                txtResult .setText("");
            }
        }
    }                                       

    private void txtActionPerformed(java.awt.event.ActionEvent evt) {                                    
        
        
    }                                   
    DefaultListModel<String> mod;
    LinkedList<Word> arr = new LinkedList<>();
    private void formWindowOpened(java.awt.event.WindowEvent evt) {                                  
        mod = new DefaultListModel<>();
        arr = DM.filterWord("");
        list.setModel(mod);
        arr.forEach((i) -> {
            mod.addElement(i.getWord());
        });
    }                                 

    private void txtKeyTyped(java.awt.event.KeyEvent evt) {                             
        String text = txt.getText();
        text+=evt.getKeyChar();
        text= text.toLowerCase().trim();
        mod = new DefaultListModel<>();
        arr = DM.filterWord(text);
        list.setModel(mod);
        arr.forEach((Word i) -> {
            mod.addElement(i.getWord());
        });
        
            if (mod.size()>0) {
                list.setSelectedIndex(0);
                javax.swing.JScrollBar sb = sp.getVerticalScrollBar();
                sb.setValue(0);
                return ;
            }
        
        txtResult.setText("THIS WORD NOT FOUND !");
        arr = null;
    }                            

    private void listValueChanged(javax.swing.event.ListSelectionEvent evt) {                                  
        // TODO add your handling code here:
        if(!list.isSelectionEmpty()){
            int index = list.getSelectedIndex();
            Word obj=arr.get(index);
            txtResult.setText(obj.getMean());
        }
    }                                 

    private void listMouseEntered(java.awt.event.MouseEvent evt) {                                  
        // TODO add your handling code here:
        
    }                                 

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify                     
    private javax.swing.JButton jAdd;
    private javax.swing.JButton jDelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jReplace;
    private javax.swing.JButton jSave;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jSearch;
    private javax.swing.JList<String> list;
    private javax.swing.JScrollPane sp;
    private javax.swing.JTextField txt;
    private javax.swing.JTextPane txtResult;
    // End of variables declaration                   
}
