/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dictionary;

import java.util.LinkedList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Tu Nguyen
 */
public class JFrame extends javax.swing.JFrame {

    /**
     * Creates new form JFrame
     */
    public JFrame() {
        setTitle("Dictionary");
        setLocationRelativeTo(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JTFSearch = new javax.swing.JTextField();
        jSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jWord = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jMean = new javax.swing.JTextArea();
        jAdd = new javax.swing.JButton();
        jDelete = new javax.swing.JButton();
        jReplace = new javax.swing.JButton();
        jSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JTFSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFSearchActionPerformed(evt);
            }
        });

        jSearch.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tu Nguyen\\Documents\\NetBeansProjects\\Dictionary\\icon\\search.png")); // NOI18N
        jSearch.setText("Search");
        jSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchActionPerformed(evt);
            }
        });

        jWord.setColumns(20);
        jWord.setRows(5);
        jScrollPane1.setViewportView(jWord);

        jMean.setColumns(20);
        jMean.setRows(5);
        jScrollPane2.setViewportView(jMean);

        jAdd.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tu Nguyen\\Documents\\NetBeansProjects\\Dictionary\\icon\\add.png")); // NOI18N
        jAdd.setText("Add");
        jAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddActionPerformed(evt);
            }
        });

        jDelete.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tu Nguyen\\Documents\\NetBeansProjects\\Dictionary\\icon\\delete.png")); // NOI18N
        jDelete.setText("Delete");
        jDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteActionPerformed(evt);
            }
        });

        jReplace.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tu Nguyen\\Documents\\NetBeansProjects\\Dictionary\\icon\\icons8-edit-file-50.png")); // NOI18N
        jReplace.setText("Replace");
        jReplace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jReplaceActionPerformed(evt);
            }
        });

        jSave.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tu Nguyen\\Documents\\NetBeansProjects\\Dictionary\\icon\\icons8-save-50.png")); // NOI18N
        jSave.setText("Save");
        jSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jAdd)
                        .addGap(18, 18, 18)
                        .addComponent(jDelete)
                        .addGap(30, 30, 30)
                        .addComponent(jReplace)
                        .addGap(33, 33, 33)
                        .addComponent(jSave)
                        .addGap(0, 32, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(JTFSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jSearch)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jDelete)
                        .addComponent(jSave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jAdd))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jReplace, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    JFrameAdd jfa;
    private void jAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddActionPerformed
        // TODO add your handling code here:
        jfa =new JFrameAdd();
    }//GEN-LAST:event_jAddActionPerformed

    private void jDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteActionPerformed
        // TODO add your handling code here:
        JFrameDelete jfd;
        jfd=new JFrameDelete();
    }//GEN-LAST:event_jDeleteActionPerformed

    private void jReplaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jReplaceActionPerformed
        // TODO add your handling code here:
        JFrameReplace jfr;
        jfr=new JFrameReplace();
    }//GEN-LAST:event_jReplaceActionPerformed
    DictionaryManagement DM=new DictionaryManagement();
    private void jSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveActionPerformed
        // TODO add your handling code here:
        DM.save();
        JOptionPane.showMessageDialog(rootPane, "Lưu thành công!");
    }//GEN-LAST:event_jSaveActionPerformed

    private void jSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchActionPerformed
        // TODO add your handling code here:
        if(JTFSearch.getText().trim().equals("")==true){
            JOptionPane.showMessageDialog(rootPane, "Hãy nhập từ cần tra");
        }
        else {
            if(DM.dictionaryLookup(JTFSearch.getText().trim())==true){
                String a=DM.JMean1(JTFSearch.getText().trim());
                jMean.setText(a);
            }
            else {
                JOptionPane.showMessageDialog(rootPane, "Từ không có trong từ điển!");
                jMean.setText("");
            }
        }
    }//GEN-LAST:event_jSearchActionPerformed

    DefaultListModel<String> mod;
    LinkedList<Word> arr = new LinkedList<>();
    private void JTFSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFSearchActionPerformed
//        // TODO add your handling code here:
//        mod = new DefaultListModel<>();
//        arr = DM.filterWord("");
//        list.setModel(mod);
//        arr.forEach((i) -> {
//            mod.addElement(i.getWord());
//        });
    }//GEN-LAST:event_JTFSearchActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame().setVisible(true);
            }
        });
    }
    private javax.swing.JList<String> list;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTFSearch;
    private javax.swing.JButton jAdd;
    private javax.swing.JButton jDelete;
    private javax.swing.JTextArea jMean;
    private javax.swing.JButton jReplace;
    private javax.swing.JButton jSave;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jSearch;
    private javax.swing.JTextArea jWord;
    // End of variables declaration//GEN-END:variables
}
