
package dictionary;


import java.util.LinkedList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;


public class JFrame extends javax.swing.JFrame {

    /**
     * Creates new form JFrame
     */
    public JFrame() {
        setTitle("Dictionary");
//        setLocationRelativeTo(null);
        setLocation(700, 300);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt = new javax.swing.JTextField();
        jSearch = new javax.swing.JButton();
        jAdd = new javax.swing.JButton();
        jDelete = new javax.swing.JButton();
        jReplace = new javax.swing.JButton();
        jSave = new javax.swing.JButton();
        sp = new javax.swing.JScrollPane();
        list = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResult = new javax.swing.JTextPane();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jButton1.setText("jButton1");

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tu Nguyen\\Documents\\NetBeansProjects\\Dictionary\\icon\\bg3.png")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtActionPerformed(evt);
            }
        });
        txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtKeyTyped(evt);
            }
        });
        getContentPane().add(txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 76, 127, 40));

        jSearch.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tu Nguyen\\Documents\\NetBeansProjects\\Dictionary\\icon\\search.png")); // NOI18N
        jSearch.setText("Search");
        jSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchActionPerformed(evt);
            }
        });
        getContentPane().add(jSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        jAdd.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tu Nguyen\\Documents\\NetBeansProjects\\Dictionary\\icon\\add.png")); // NOI18N
        jAdd.setText("Add");
        jAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddActionPerformed(evt);
            }
        });
        getContentPane().add(jAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jDelete.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tu Nguyen\\Documents\\NetBeansProjects\\Dictionary\\icon\\delete.png")); // NOI18N
        jDelete.setText("Delete");
        jDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(jDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jReplace.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tu Nguyen\\Documents\\NetBeansProjects\\Dictionary\\icon\\icons8-edit-file-50.png")); // NOI18N
        jReplace.setText("Replace");
        jReplace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jReplaceActionPerformed(evt);
            }
        });
        getContentPane().add(jReplace, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        jSave.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tu Nguyen\\Documents\\NetBeansProjects\\Dictionary\\icon\\icons8-save-50.png")); // NOI18N
        jSave.setText("Save");
        jSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveActionPerformed(evt);
            }
        });
        getContentPane().add(jSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, 30));

        list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                listMouseEntered(evt);
            }
        });
        list.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listValueChanged(evt);
            }
        });
        sp.setViewportView(list);

        getContentPane().add(sp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 161, 254));

        txtResult.setContentType("text/html"); // NOI18N
        txtResult.setFocusable(false);
        jScrollPane1.setViewportView(txtResult);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 273, 254));

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tu Nguyen\\Documents\\NetBeansProjects\\Dictionary\\icon\\voice1.png")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 30, 30));

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tu Nguyen\\Documents\\NetBeansProjects\\Dictionary\\icon\\translate.png")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 50, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tu Nguyen\\Documents\\NetBeansProjects\\Dictionary\\icon\\bg3.png")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 0, 590, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddActionPerformed
        // TODO add your handling code here:
        DM.save();
        JFrameAdd jfa;
        jfa =new JFrameAdd();
        DM.save();
    }//GEN-LAST:event_jAddActionPerformed

    private void jDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteActionPerformed
        // TODO add your handling code here:
        DM.save();
        JFrameDelete jfd;
        jfd=new JFrameDelete();
        DM.save();
    }//GEN-LAST:event_jDeleteActionPerformed

    private void jReplaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jReplaceActionPerformed
        // TODO add your handling code here:
        DM.save();
        JFrameReplace jfr;
        jfr=new JFrameReplace();
        DM.save();
        
    }//GEN-LAST:event_jReplaceActionPerformed
    DictionaryManagement DM=new DictionaryManagement();
    private void jSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveActionPerformed
        // TODO add your handling code here:
        DM.save();
        JOptionPane.showMessageDialog(rootPane, "Lưu thành công!");
    }//GEN-LAST:event_jSaveActionPerformed

    private void jSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchActionPerformed
        // TODO add your handling code here:
        if(txt.getText().trim().equals("")==true){
            JOptionPane.showMessageDialog(rootPane, "Hãy nhập từ cần tra");
        }
        else {
            if(DM.dictionaryLookup(txt.getText().trim())==true){
                String a=DM.JMean1(txt.getText().trim());
                txtResult.setText(a);
            }
            else {
                JOptionPane.showMessageDialog(rootPane, "Từ không có trong từ điển!");
                txtResult .setText("");
            }
        }
    }//GEN-LAST:event_jSearchActionPerformed

    private void txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtActionPerformed
        
        
    }//GEN-LAST:event_txtActionPerformed
    DefaultListModel<String> mod;
    LinkedList<Word> arr = new LinkedList<>();
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        mod = new DefaultListModel<>();
        arr = DM.filterWord("");
        list.setModel(mod);
        arr.forEach((i) -> {
            mod.addElement(i.getWord());
        });
    }//GEN-LAST:event_formWindowOpened

    private void txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKeyTyped
        String text = txt.getText();
        text+=evt.getKeyChar();
        text= text.toLowerCase().trim();
        mod = new DefaultListModel<>();
        arr = DM.filterWord(text);
        list.setModel(mod);
        arr.forEach((Word i) -> {
            mod.addElement(i.getWord());
        });
        
            if (mod.size()>0) {
                list.setSelectedIndex(0);
                javax.swing.JScrollBar sb = sp.getVerticalScrollBar();
                sb.setValue(0);
                return ;
            }
        
        txtResult.setText("THIS WORD NOT FOUND !");
        arr = null;
    }//GEN-LAST:event_txtKeyTyped

    private void listValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listValueChanged
        // TODO add your handling code here:
        if(!list.isSelectionEmpty()){
            int index = list.getSelectedIndex();
            Word obj=arr.get(index);
            txtResult.setText(obj.getMean());
        }
    }//GEN-LAST:event_listValueChanged

    private void listMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_listMouseEntered

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(!list.isSelectionEmpty()){
            int index = list.getSelectedIndex();
            Word obj=arr.get(index);
            txtResult.setText(obj.getMean());
            new DictionaryManagement(obj.getWord());
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JFrameAPI jfa;
        jfa=new JFrameAPI();
    }//GEN-LAST:event_jButton3ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAdd;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jDelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jReplace;
    private javax.swing.JButton jSave;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jSearch;
    private javax.swing.JList<String> list;
    private javax.swing.JScrollPane sp;
    private javax.swing.JTextField txt;
    private javax.swing.JTextPane txtResult;
    // End of variables declaration//GEN-END:variables
}
